### ISSUE TITLE
Shortcut for hide and show application

### ISSUE THREAD

**Issue by livelazily** [egoist/devdocs-app#13]
Any plan to support global shortcut for hide and show application?

**Comment by egoist** [comment]
That sounds good, I might add it later, you can send a PR if you can't wait for this ;D

**Comment by egoist** [comment]
In [v0.4.0](https://github.com/egoist/devdocs-app/releases/tag/v0.4.0) we add a default shortcut, planning to support custom shortcut in the future though :)

**Comment by Spy-Seth** [comment]
Allowing user to customize or disable it will be cool 👍 The current settings conflict with one of my shortcut in my IDE

**Comment by egoist** [comment]
@Spy-Seth see https://github.com/egoist/devdocs-app/releases/tag/v0.5.0, it's now disabled by default, will be customizable in the future.

**Comment by Spy-Seth** [comment]
Good news!
