### ISSUE TITLE
Add find in page

### ISSUE THREAD

**Issue by rnovacek** [egoist/devdocs-app#16]
Some of the documentation pages I use are quite long and it would help me greatly if I can search the page.

Standard browser search box would be enough and if it can also highlight occurrences of the searched word, it would be totally awesome.

**Comment by egoist** [comment]
I see, this could be useful

**Comment by ELLIOTTCABLE** [comment]
Yeah, this is the single biggest thing I'm missing! Is it complicated to add to a WebView app like this?

**Comment by igauravsehrawat** [comment]
I can take this up.
Found https://electron.atom.io/docs/api/web-contents/#contentsfindinpagetext-options
from https://github.com/electron/electron/issues/2037

Thanks

**Comment by j-f1** [comment]
@igauravsehrawat You might want to look at [nakajmg/electron-search-text](https://github.com/nakajmg/electron-search-text) or [rhysd/electron-in-page-search](https://github.com/rhysd/electron-in-page-search).

**Comment by egoist** [comment]
Here's a work in progress: https://github.com/egoist/devdocs-app/pull/26 99.9% is working.

**Comment by j-f1** [comment]
@egoist Why do you have to use the native title bar?

**Comment by egoist** [comment]
@j-f1 in order to add *in-page search*, now we load devdocs.io with a `<webview>` tag. And we can't drag elements inside webview to move the window, see https://github.com/electron/electron/issues/6791

**Comment by egoist** [comment]
This feature just landed in [v0.4.0](https://github.com/egoist/devdocs-app/releases/tag/v0.4.0)

**Comment by egoist** [comment]
@j-f1 Re-introduce a custom titlebar 😅

![2017-06-14 3 05 49](https://user-images.githubusercontent.com/8784712/27119726-924c9994-5113-11e7-84e3-fbdff2fb0d03.png)

**Comment by j-f1** [comment]
Thanks 😄

**Comment by ELLIOTTCABLE** [comment]
<'3
