### ISSUE TITLE
Automate GitHub release

### ISSUE THREAD

**Issue by egoist** [egoist/devdocs-app#18]
https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts

**Comment by Meadowcottage** [comment]
Been looking into this for a while now. Best method I have been using is using a [nuts](https://nuts.gitbook.com/) server running on [Heroku](https://heroku.com) server. Updating to NSIS will make window auto-updating much easier for Windows. 😄

If you want an example set up. I've been testing on here for a while. Mac system works, however Windows is still having issues. [github.com/meadowcottage/testelectron](https://github.com/meadowcottage/testelectron/)

**Comment by egoist** [comment]
Actually I didn't mean `auto-update` but `auto-release to github release`, but it's nice if you can achieve that too.

**Comment by Meadowcottage** [comment]
Ah okay. I'll add it as a separate issue then 😛

**Comment by alcat2008** [comment]
@Meadowcottage For Windows, [electron-simple-updater](https://github.com/megahertz/electron-simple-updater) can do that. I hava just completed the testing.

**Comment by j-f1** [comment]
I’ve done this with [my electron app](https://github.com/Charcoal-SE/coal) that wraps a website if you’re interested in seeing the technique.

**Comment by Positive07** [comment]
I have used [electron-builder](https://github.com/electron-userland/electron-builder) to accomplish this behaviour and it is my current recommended build tool. It's actively maintained, and has releases at least per week! (most of the time backwards compatible)

**Comment by Meadowcottage** [comment]
I have been trying myself to set up auto updates myself using `electron-builder` as well.
Been trying to set up them more recently since they have updated their updater system to auto search from github releases.
