### ISSUE TITLE
the blank on the left of  search box

### ISSUE THREAD

**Issue by jetz** [egoist/devdocs-app#19]
Version: 0.2.1
OS: Ubuntu 16.04

As the picture shows, there is a blank on the left, it narrows the search box and hide parts of my text, please align to left to increase size of the search box.

![qq 20170307120955](https://cloud.githubusercontent.com/assets/1232624/23641644/7cd8fe80-0330-11e7-9064-42d9089f55e3.png)

**Comment by egoist** [comment]
Would you like to send a PR for this 😄

**Comment by jetz** [comment]
@egoist Um, I have no any experience in developing electron apps, so 爱莫能助 :rofl:

**Comment by egoist** [comment]
Fixed in a new release: https://github.com/egoist/devdocs-app/releases/tag/v0.2.2
