### ISSUE TITLE
CSS override

### ISSUE THREAD

**Issue by curtisblackwell** [egoist/devdocs-app#20]
Would love to be able to make small tweaks like content container width and font family/size. Are you interested in this feature?

**Comment by egoist** [comment]
Do you mean custom css? That sounds good.

But before that I think we should migrate this app to load `devdocs.io` with a `webview` tag in order to add other pages like `preference page`.

**Comment by curtisblackwell** [comment]
I do mean custom CSS.

**Comment by egoist** [comment]
Custom CSS/JS is supported, check out https://github.com/egoist/devdocs-app/releases/tag/v0.3.0
