### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by Meadowcottage** [egoist/devdocs-app#22]
Having a system to automatically check the current version to see if there's a new one available would be nice.
Already covered some of this in #18 😄

**Comment by Positive07** [comment]
Isn't this fixed @egoist?

**Comment by egoist** [comment]
@Positive07 Not yet.

**Comment by egoist** [comment]
Added a simple updater which only notifies you of new release and you can click it to visit github release page. https://github.com/egoist/devdocs-app/releases/tag/v0.5.1

**Comment by Positive07** [comment]
Why aren't you just using [electron-updater](https://github.com/electron-userland/electron-builder/wiki/Auto-Update#quick-setup-guide)?

I can make a PR if you want fixing both this issue and #18

**Comment by egoist** [comment]
@Positive07 that would be great.

**Comment by egoist** [comment]
@Positive07  hmm, seems we need a code-signing certificate (which I don't have) for that on macOS

**Comment by Positive07** [comment]
Mmmm lets try it, at worst we will get automatic builds only (and Windows only autoupdates)
