### ISSUE TITLE
Default content font size prohibitively too small for reading, while custom.css not working.

### ISSUE THREAD

**Issue by Annis-Monadjem** [egoist/devdocs-app#28]
@egoist: To increase content font size I have saved 
>._list-item, ._content {
    font-size: 1rem !important;
}
>
in `custom.css`; but font has Not changed. Am i doing something wrong? And so how is it possible to increase content font size? I am currently using devdocs.io `v0.5.1`. I have tweeted different sizes 1rem, 5rem, 10rem - but none increase or otherwise change the size of font content. 
Again, the small font size that is used by default in devdocs.io is prohibitive so effectively i end up not using devdocs at all. It would be really nice to have this feature work.

**Comment by egoist** [comment]
What's the platform you're on? After updating the `custom.css` you need a refresh.

**Comment by egoist** [comment]
I'll add a menu item to let you increase/decrease font-size directly in next version.

**Comment by egoist** [comment]
Added. 
<img width="289" alt="2017-06-15 11 49 45" src="https://user-images.githubusercontent.com/8784712/27164569-c397ce08-51c0-11e7-8d41-d9383341eb0d.png">

**Comment by Annis-Monadjem** [comment]
Hi @egoist: Thanks for your replies - but its still Not working for me. 

After placing the above css code in `custom.css` and after tweeking it to e.g. `1.4em` or `5em` i do refresh and restart devdocs, but font size has Not changed a bit. 

My platform is: Peppermint 7 64bit / Linux 4.4.0-79-generic (effectively it is Ubuntu 16.04) so I have loaded the most recent `DevDocs_0.5.1_amd64.deb` but I'm not seeing the above screen-shot you have. What i see under the View is: Search in Page, Reload and Toggle Developer Tools.

Any suggestions, please? Would very much like to improve reading experience. Best.

**Comment by Positive07** [comment]
Try latest 0.6.0 (but if you have 0.5.1 you should have those entries)

**Comment by egoist** [comment]
`increase/decrease text size` is supposed to be shipped in `v0.6.0` and it's not yet released. 😅

**Comment by Thibaut** [comment]
Hi there

Note that CSS class names in DevDocs are subject to change at any time, so I wouldn't recommend things like `._list-item, ._content { ... }`, as it's likely to break at some point in the future.

The entire UI uses `rem`-based units, so you can scale it up & down by simply adjusting the root font-size: `html { font-size: 112%; }` (the default is 100%)

**Comment by egoist** [comment]
@Thibaut Thanks for the note, the current solution is `body {zoom: $zoom !important}`

**Comment by Thibaut** [comment]
👍 that seems to be equivalent except it also scales native elements (scroll bars, checkboxes, etc.).

**Comment by Annis-Monadjem** [comment]
@egoist: I'm not seeing any change when applying `body {zoom: $zoom !important` (am i using it correctly?). While when i apply `._list-item, ._content { ... }` i am thrown the following attached error:
![error_devdocs](https://user-images.githubusercontent.com/13934141/27259857-1a435c64-541d-11e7-8af7-a932a918c0dc.png)
Any suggestions? Am i doing it right?

**Comment by egoist** [comment]
Try latest release. https://github.com/egoist/devdocs-app/releases/tag/v0.6.0-rc.1

**Comment by Annis-Monadjem** [comment]
@egoist: Thanks it's working.

**Comment by egoist** [comment]
Closing since it's fixed.

**Comment by jottr** [comment]
This issue seems to be back on`v0.7.1`. 

Please reopen.
