### ISSUE TITLE
Main search input won't be auto-focused after in-page search dismissed.

### ISSUE THREAD

**Issue by psjay** [egoist/devdocs-app#32]
Version: 0.5.1
OS: macOS 10.12.5

Reproduce steps:
1. Press Command+F to active in-page search;
2. Press ESC to dismiss in-page search;
3. Main search input won't be focused until clicking any area in the main window.

**Comment by psjay** [comment]
This issue has been fixed but another similar issue appears:

When using Cmd+TAB to switch to Devdocs-app, search bar is not active unless you click any area in the main window.

**Comment by egoist** [comment]
It should be completely fixed in [v0.6.3](https://github.com/egoist/devdocs-app/releases/tag/v0.6.3)
